name: Meetup Application
description: Add a Meetup Application to track.
title: "[Meetup]: "
labels: ["Meetup", "application", "meetup-application", "Awaiting Triage"]
projects: ["WordPress/64"]
assignees: [""]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this Meetup Application!
  - type: input
    id: meetup-title
    attributes:
      label: Meetup City or Event Name
      description: Meetup City or Event Name
      placeholder: <city>, <country>
    validations:
      required: true
  - type: input
    id: meetup-tracker
    attributes:
      label: Meetup Tracker Link
      description: Add the Meetup Tracker Link here.
    validations:
      required: true
  - type: input
    id: meetup-helpscout
    attributes:
      label: Meetup HelpScout Link
      description: Add the Meetup HelpScout Link here.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Next steps

        - [ ] Please assign the issue to the team member and make sure to mark the issue ```To Do```
        - [ ] Assignee (Team Member) will mark the issue as ```In Progress``` and perform the vetting taks on the tracker and HS as indicated on the handbook
        - [ ] Once the vetting is completed mark the issue as ```In Review```

        ## Public vs Private

          - Use comments for questions about the process and changes or to indicate delays, holding situation.
          - Avoid discussing the community or the organiser in comments on Github. Even if there are doubts about some applications.
          - We do not post vetting notes publicly and ensure such notes are strictly in the tracker or HelpScout.

        ## Useful Resources

          - [Application Review](https://make.wordpress.org/community/handbook/community-deputy/resources-and-tools/application-review/)
          - [Most Common Cases](https://make.wordpress.org/community/handbook/community-deputy/resources-and-tools/application-review/#most-common-cases-quick-step-by-step-guide)
          - [Video tutorials](https://make.wordpress.org/community/handbook/community-deputy/resources-and-tools/application-review/#quick-step-by-step-video-tutorial-for-application-review)
